"""Criando tabelas iniciais

Revision ID: d82d4c8688f6
Revises: 
Create Date: 2025-04-14 10:08:04.277755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd82d4c8688f6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tarefa_id', table_name='tarefa')
    op.drop_table('tarefa')
    op.drop_index('ix_usuario_email', table_name='usuario')
    op.drop_index('ix_usuario_id', table_name='usuario')
    op.drop_table('usuario')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('usuario_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='usuario_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_usuario_id', 'usuario', ['id'], unique=False)
    op.create_index('ix_usuario_email', 'usuario', ['email'], unique=True)
    op.create_table('tarefa',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_criacao', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pendente', 'concluida', name='statusenum'), autoincrement=False, nullable=False),
    sa.Column('data_conclusao', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name='tarefa_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tarefa_pkey')
    )
    op.create_index('ix_tarefa_id', 'tarefa', ['id'], unique=False)
    # ### end Alembic commands ###
